### PR TITLE
Firefox compatibility (replace old storage system with IndexedDB)

### LINKED ISSUE #75: Firefox support?
It would be great if the extension supported firefox and other browsers.

### PR DESCRIPTION
**Pull request by viktorstrate**
This fix works perfectly with Chrome. The plugin can now be loaded in firefox, but when trying to download cached files, Uddata.com appears in a window (as in chrome), and then nothing happends, and no files are downloaded as expected. But it is better than not working with Firefox at all.

This resolves #75 

Currently the code could need some cleanup, and possibly a fix for cached files in Firefox.

### CODE REVIEW

**Comment by RasmusRendal** [comment]
I've only been able to have a quick look, but it looks like some quality code. I'll be back at the hotel later tonight, and I can give it a closer look. But damn, good job mate.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by viktorstrate** [comment]
I'm glad to hear that 😊
Let me know if there is somthing you think could be improved, or somthing i am missing, regarding this pull request.

**Comment by jbjjbjjbj** [comment]
Hey this looks really nice :-D. But i noticed that the line 57 chrashes the background script, because the storeFiles function is gone. I probably did somthing wrong, but i can't see how i would work.

Tip: we made a dedicated dev mode you can activate and then print stuff to the console with debugLog();. Just use the konami kode while in the settingsmenu.

**Comment by viktorstrate** [comment]
I have removed the storeFiles function from line 57, and replaced console logs with debugLog. Need implementation of the konami code xD

**Comment by jbjjbjjbj** [comment]
Just testet it in chrome and everything besides the storage counter works perfectly :-D. 

Like you said the file storage does not work in firefox, but everything else like the schedule backup, homework mark and theming works nicely :+1:

**Comment by viktorstrate** [comment]
I have updated the branch to show the total size of the cached files, under preferences.

**Comment by jbjjbjjbj** [comment]
Nice, uddata is down so can't test it right now. I would say this is ready to be merged to development, but i can't make that decision on my own. @RasmusRendal @Benjadahl.

One problem is that we can't release this to the firefox market place. Last time we were rejected because this is only made for people who use uddata. We can get a signed release file from mozilla which we can release ourself, but the problem with this is that users need to manualy check for updates and install them.

**Comment by RasmusRendal** [comment]
Well, it works in Chromium. In Firefox, the Dashboard does not work at all, and neither does opening settings from the UDDATA page itself. But as nothing is broken in Chromium, and we got away from the horrible hack that was our previous file-saving system, why not merge anyway.

**Comment by viktorstrate** [comment]
@RasmusRendal The extension works decently in Firefox for me, the dashboard works too. The scroll effect when you click on a lesson, does not however, but theres an error in the console.

I have tested the extension in Firefox 56 and 57, without major problems. I added the extension by going to `about:debugging`, and pressed `Load Temporary Add-on`

In Firefox 57, even downloading files works, the links doesn't however, but I think it is easily fixed.

### Screenshot from the upcomming release of Firefox quantom

Screenshot

**Comment by jbjjbjjbj** [comment]
Yeah i noticed the not working link. I can do the signing of the extension so we can get a nice extension package thingy. @RasmusRendal @Benjadahl we are ready for at merge, right?

**Pull request merged**
