### PR TITLE
Fix download of cached files in Firefox

### PR DESCRIPTION
**Pull request by viktorstrate**
Right now file download works in Firefox but not in Chrome.
This is because blobs can't be passed from background.js to dashboard.js
through "chrome.runtime.sendMessage" in Chrome, this does however work in Firefox.

Possible fix would be to use the previous code for Chrome and the new
for Firefox, is there a way to detect wich browser is being used?

### CODE REVIEW

**Comment by viktorstrate** [comment]
This should be ready for push now, if somone wants to review it?

**Comment by jbjjbjjbj** [comment]
Woow nice :-). I will test this as fast as possible. But is it posible to merge this with the develop branch instead of master.

By the way @viktorstrate I've uploaded the plugin to the firefox extension store.

**Comment by viktorstrate** [comment]
@jbjjbjjbj Yeah I saw that, looks good ^^

**Comment by viktorstrate** [comment]
@jbjjbjjbj I have changed the branch from master to development

**Comment by jbjjbjjbj** [comment]
Thanks, haven't testet the pull request yet, sorry. Will be done by the end of this week

**Comment by jbjjbjjbj** [comment]
Hey just tested the pull request, but i had some problems. I don't know if this is just my configuration but the uddataplus tabs being used to download files does not close then they are done. Another problem is that the scrolling on the dashboard does not work.

**Comment by viktorstrate** [comment]
This is problems with Firefox only, and they aren't new problems. There's an error in the console about the scrolling thing, and I don't know why the windows aren't closing. 

But it's not related to this pull request😊

**Comment by jbjjbjjbj** [comment]
Hey just tested the download once more and found the reason for the not closing tabs. Then they are not closing i get at console message which says "scripts cannot close windows they had not opened"
This happens in firefox 56 and 57 with a fresh profile.

Screenshot of console https://imgur.com/a/oGoaq

**Comment by viktorstrate** [comment]
The best thing, would be to find a way to download the files, in the background.

**Comment by jbjjbjjbj** [comment]
Yeah :-(

**Comment by viktorstrate** [comment]
Can you please merge this, as the problems discussed above, is not related to this pull request?

**Comment by jbjjbjjbj** [comment]
Yeah sorry. Will try and do this tomorow.

**Pull request merged**
